# Manipulating DataFrames

Remember to import Pandas at the start.

In [1]:
import pandas as pd

## Melting the Data

In the last workbook we worked with some data about Tuberculosis (TB) cases.

In [2]:
df = pd.DataFrame(
    {
        '2011':[7000,5800,15000],
        '2012':[6900,6000,14000],
        '2013':[7000,6200,13000]
    },
    index = ['France','Germany','United States of America'],
)

df

                           2011   2012   2013
France                     7000   6900   7000
Germany                    5800   6000   6200
United States of America  15000  14000  13000

We already know how to find the maximum value for each row or column:

In [3]:
df.max()

2011    15000
2012    14000
2013    13000
dtype: int64

But suppose we want to find the maximum value across all the data points. 
Having got the maximum for each column we could now find the maximum across the three numerical values in this Series:

In [4]:
df.max().max()

15000

But this approach is not reliable. For example, if we had some ``pd.NA`` values and wanted to find the average then calculating the average for each column and then taking the average of this may produce an incorrect answer. Instead, we should change the way that the data is presented so that it is easier to perform calculations across all of the data. This can be achieved with the ``melt()`` method.

We'll use a different DataFrame to illustrate how the method works.

In [5]:
df = pd.DataFrame(
    {
        'a': ['a1', 'a2', 'a3'],
        'b': ['b1', 'b2', 'b3'],
        'c': ['c1', 'c2', 'c3']
    },
    index = [1,2,3],
)

df

    a   b   c
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

In [6]:
df.melt(ignore_index=False)

  variable value
1        a    a1
2        a    a2
3        a    a3
1        b    b1
2        b    b2
3        b    b3
1        c    c1
2        c    c2
3        c    c3

This is exactly the same data but organised in a different way. We have taken the column names and put these into a new column, ``variable``. Then the ``value`` column records the data that belongs to each column. 

In this example we had specified an index for our DataFrame.
``ignore_index=False`` tells Pandas that the index values are important to us. 
If instead we had started with those index values just as another column then the parameter ``id_vars`` tells Pandas which column

In [7]:
df = pd.DataFrame(
    {
        'N': [1,2,3],
        'a': ['a1', 'a2', 'a3'],
        'b': ['b1', 'b2', 'b3'],
        'c': ['c1', 'c2', 'c3']
    },
)

df

   N   a   b   c
0  1  a1  b1  c1
1  2  a2  b2  c2
2  3  a3  b3  c3

In [8]:
df.melt(id_vars='N')

   N variable value
0  1        a    a1
1  2        a    a2
2  3        a    a3
3  1        b    b1
4  2        b    b2
5  3        b    b3
6  1        c    c1
7  2        c    c2
8  3        c    c3

Trying different arguments for ``id_vars`` in the next couple of cells helps to show how the method works, although these DataFrames are probably useless!

In [9]:
df.melt()

   variable value
0         N     1
1         N     2
2         N     3
3         a    a1
4         a    a2
5         a    a3
6         b    b1
7         b    b2
8         b    b3
9         c    c1
10        c    c2
11        c    c3

In [10]:
df.melt(id_vars=['a', 'b'])

    a   b variable value
0  a1  b1        N     1
1  a2  b2        N     2
2  a3  b3        N     3
3  a1  b1        c    c1
4  a2  b2        c    c2
5  a3  b3        c    c3

We can change the headings from the default 'variable' and 'value'.

In [11]:
df.melt(id_vars='N', var_name='my_column_heading', value_name='my_data_value')

   N my_column_heading my_data_value
0  1                 a            a1
1  2                 a            a2
2  3                 a            a3
3  1                 b            b1
4  2                 b            b2
5  3                 b            b3
6  1                 c            c1
7  2                 c            c2
8  3                 c            c3

## Exercise 1
Use the melt() function on the TB DataFrame and find the maximum number of infections in any single country in any single year.

In [12]:
df = pd.DataFrame(
    {
        'country': ['France','Germany','United States of America'],
        '2011':[7000,5800,15000],
        '2012':[6900,6000,14000],
        '2013':[7000,6200,13000]
    },
)

df

                    country   2011   2012   2013
0                    France   7000   6900   7000
1                   Germany   5800   6000   6200
2  United States of America  15000  14000  13000

In [14]:
df2 = df.melt(id_vars='country', var_name='Year', value_name='TB Cases')
df2

                    country  Year  TB Cases
0                    France  2011      7000
1                   Germany  2011      5800
2  United States of America  2011     15000
3                    France  2012      6900
4                   Germany  2012      6000
5  United States of America  2012     14000
6                    France  2013      7000
7                   Germany  2013      6200
8  United States of America  2013     13000

In [24]:
for year in df2['Year'].unique():
    print(f'{year}: {df2[df2["Year"]==year]["TB Cases"].max()}')

2011: 15000
2012: 14000
2013: 13000

## Pivoting the Data

Sometimes the opposite situation arises. The method ``pivot()`` also reshapes the data but this time by creating new columns.

In [25]:
df = pd.DataFrame(
    {
        'a': ['a1', 'a2', 'a3'],
        'b': ['b1', 'b2', 'b3'],
        'c': ['c1', 'c2', 'c3']
    },
    index=[1,2,3]
)

df

    a   b   c
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

In [26]:
df2 = df.melt(ignore_index=False)

df2

  variable value
1        a    a1
2        a    a2
3        a    a3
1        b    b1
2        b    b2
3        b    b3
1        c    c1
2        c    c2
3        c    c3

In [27]:
df3 = df2.pivot(columns='variable')

df3

         value
variable     a   b   c
1           a1  b1  c1
2           a2  b2  c2
3           a3  b3  c3

Again, if we wanted to use a column in place of the index we can do this by passing in an additional argument.

In [28]:
# this cell simply prepares the DataFrame that we want to pivot in the next cell
df = df2.reset_index()
df.rename(columns={'index':'N'}, inplace=True)
df

   N variable value
0  1        a    a1
1  2        a    a2
2  3        a    a3
3  1        b    b1
4  2        b    b2
5  3        b    b3
6  1        c    c1
7  2        c    c2
8  3        c    c3

In [29]:
df.pivot(index='N', columns='variable')

         value
variable     a   b   c
N
1           a1  b1  c1
2           a2  b2  c2
3           a3  b3  c3

## Exercise 2

Let us have a look at some data on the amount of pollution for different cities (New York, London and Beijing).

Pivot the DataFrame into the format 

|city|large|small|
|---|---|---|
|Beijing| | |
|London| | |
|New York| | |

In [30]:
df_pollution = pd.DataFrame(
    {
        'size':['large','small','large','small','large','small'],
        'amount':[23,14,22,16,121,56]
    },
    index=['New York','New York','London','London','Beijing','Beijing']
)

df_pollution

           size  amount
New York  large      23
New York  small      14
London    large      22
London    small      16
Beijing   large     121
Beijing   small      56

In [31]:
df_p2 = df_pollution.pivot(columns='size')
df_p2

         amount
size      large small
Beijing     121    56
London       22    16
New York     23    14

## Joining DataFrames

We've already seen how to add new columns to a DataFrame. Joins allow us to create a new DataFrame from two (or more) existing DataFrames.

If we have two tables that have a common attribute (or a set of attributes) then we can join them together.

In [32]:
df1 = pd.DataFrame({
    'country':['France','Germany','United States of America'],
    '2011':[7000,5800,15000],
    '2012':[6900,6000,14000],
    '2013':[7000,6200,13000]})

df1

                    country   2011   2012   2013
0                    France   7000   6900   7000
1                   Germany   5800   6000   6200
2  United States of America  15000  14000  13000

In [33]:
df2 = pd.DataFrame({
    'cntry':['France','Germany','Russia'],
    '2014':[6500,5900,15500],
    '2015':[7000,7000,15000],
    '2016':[8000,6500,13300]})

df2

     cntry   2014   2015   2016
0   France   6500   7000   8000
1  Germany   5900   7000   6500
2   Russia  15500  15000  13300

We need to make sure that both DataFrames have the same column name. In this case both have a column for the country but in df2 it is spelled differently.

In [34]:
df2.rename(columns = {'cntry':'country'}, inplace = True)

df2

   country   2014   2015   2016
0   France   6500   7000   8000
1  Germany   5900   7000   6500
2   Russia  15500  15000  13300

Now we can join the two DataFrames together on the common 'country' field. We do this with the ``merge()`` method. 

### Inner Join

An inner join only keeps rows where both of the initial DataFrames have a matching value in the join column. In this case, we join on the 'country' column. df1 and df2 both contain the entry France and Germany in this column, df1 also has America, df2 also has Russia.

In [35]:
inner = pd.merge(df1,df2, on='country')
inner

   country  2011  2012  2013  2014  2015  2016
0   France  7000  6900  7000  6500  7000  8000
1  Germany  5800  6000  6200  5900  7000  6500

### Left Join
A left join keeps all of the rows from the first DataFrame, but still only keeps those from the second DataFrame where a matching value exists in the first DataFrame in the join column.

In [36]:
left = pd.merge(df1, df2, on = 'country', how = 'left')
left

                    country   2011   2012   2013    2014    2015    2016
0                    France   7000   6900   7000  6500.0  7000.0  8000.0
1                   Germany   5800   6000   6200  5900.0  7000.0  6500.0
2  United States of America  15000  14000  13000     NaN     NaN     NaN

Note that we have all the records from df1 and where there was no data available from df2 these fields have been filled with NaN (not a number) values.

### Right Join
A right join is the same as a left join except that we keep everything from the second DataFrame and only those with matching values in the join column from the first DataFrame

In [37]:
right = pd.merge(df1, df2, on = 'country', how = 'right')
right

   country    2011    2012    2013   2014   2015   2016
0   France  7000.0  6900.0  7000.0   6500   7000   8000
1  Germany  5800.0  6000.0  6200.0   5900   7000   6500
2   Russia     NaN     NaN     NaN  15500  15000  13300

We have all the records from df2 and where there was no data available from df1 these fields have been filled with NaN values.

### Outer Join
An outer join keeps all the records from both DataFrames, filling fields where no data exists with NaN.

In [38]:
outer = pd.merge(df1, df2, on = 'country', how = 'outer')
outer

,country,2011,2012,2013,2014,2015,2016
0,France,7000.0,6900.0,7000.0,6500.0,7000.0,8000.0
1,Germany,5800.0,6000.0,6200.0,5900.0,7000.0,6500.0
2,United States of America,15000.0,14000.0,13000.0,NaN,NaN,NaN
3,Russia,NaN,NaN,NaN,15500.0,15000.0,13300.0

## Grouping Data

We will use the data about passengers on board the Titanic https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv.

In [39]:
titanic = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv')
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## GroupBy- one field

Grouping the data collects together records that have the same value in the specified column.
For example, we can groupby records by 'Sex'.
The following cell first selects just the Passenger Id, Age, and Sex columns. Then we group the DataFrame by the Sex column, so this collects together rows which share the same value in this column. 
Finally, we apply ``count()`` to the DataFrame. This counts the number of values in all the other columns i.e. the PassengerId and Age columns.
The numbers in the PassengerId column are higher because some passengers do not have an age value specified in the DataFrame and the ``count()`` method does not count 'not a number' entries.

The next cell calculates the mean age of both men and women on board.

In [40]:
titanic[['PassengerId','Age', 'Sex']].groupby(['Sex']).count()

        PassengerId  Age
Sex
female          314  261
male            577  453

In [41]:
titanic[['Age', 'Sex']].groupby(['Sex']).mean()

              Age
Sex
female  27.915709
male    30.726645

## GroupBy- multiple fields
We can apply the grouping across more than one field. In the next cell we group by both the passenger's sex and whether they survived (0 means they did not survive, 1 means they survived).
When grouping over two columns the rows which have identical values in both these columns will be collected together. 
Having grouped the passenger by sex and survival we count the number of entries in the PassengerId column to see how many fall into each category. We see that a much greater proportion of the women survived than the men.

In [42]:
titanic[['Survived', 'Sex', 'PassengerId']].groupby(['Sex', 'Survived'],sort='descending').count()

                 PassengerId
Sex    Survived
female 0                  81
       1                 233
male   0                 468
       1                 109

We could also find the average age of those who survived.

In [43]:
titanic[['Sex', 'Survived', 'Age']].groupby(['Sex','Survived'],sort='descending').mean()

                       Age
Sex    Survived
female 0         25.046875
       1         28.847716
male   0         31.618056
       1         27.276022

## Rescaling a Field

Sometimes it is useful to rescale the data so that values are all between 0 and 1. Let us see how we can do this for the age. To rescale we need to take each age subtracted from the min and then we divide the result by the max - min

In [44]:
titanic['AgeRescaled'] = (titanic.Age - titanic.Age.min())/(titanic.Age.max()-titanic.Age.min())
titanic[['Age', 'AgeRescaled']].head()

    Age  AgeRescaled
0  22.0     0.271174
1  38.0     0.472229
2  26.0     0.321438
3  35.0     0.434531
4  35.0     0.434531

# Solutions to Exercises
## 1

In [45]:
df = pd.DataFrame(
    {
        'country': ['France','Germany','United States of America'],
        '2011':[7000,5800,15000],
        '2012':[6900,6000,14000],
        '2013':[7000,6200,13000]
    },
)

df2 = pd.melt(df, id_vars ='country', var_name='year', value_name='count')

round(df2['count'].mean(),1)

8988.9

## 2

In [46]:
df_pollution = pd.DataFrame(
    {   
        'size':['large','small','large','small','large','small'],
        'amount':[23,14,22,16,121,56]
    },
    index=['New York','New York','London','London','Beijing','Beijing']
)

df_new = df_pollution.pivot(columns='size')

df_new

         amount
size      large small
Beijing     121    56
London       22    16
New York     23    14