# Introduction to DataFrames

In this workbook we introduce a popular Python library that makes loading and saving data in different formats trivial. It's also very powerful for data manipulation, and thus selection. This library is: `pandas`.

We'll start with an example with the data in Python, we'll then look at loading and saving various common formats you're likely to encounter.

To use ``pandas`` we need to import it. By convention pandas is referred to by the abbreviation ``pd`` -- this isn't required but it's very common.

In [1]:
import pandas as pd

## Pandas DataFrames

`pandas` stores data in a structure it calls a DataFrame. 
Conceptually you can think of it as a table, with column headings and numbered rows.

DataFrame is a class in Python, so we create a DataFrame object by calling the constructor.
We'll use a few books for our data.
``df`` is a common variable name for a DataFrame.

In [2]:
df = pd.DataFrame({
    "title": ["Tangled Web",
              "Close Up",
              "Foundations",
              "Professional Secrets",
              "5 Times 5"],
    "author": ["Eric Mead",
               "David Stone",
               "Eberhard Riese",
               "Geoffrey Durham",
               "Richard Kaufman"],
    "price": [40, 23.1, 70, 295, 34.65]
})

df

                  title           author   price
0           Tangled Web        Eric Mead   40.00
1              Close Up      David Stone   23.10
2           Foundations   Eberhard Riese   70.00
3  Professional Secrets  Geoffrey Durham  295.00
4             5 Times 5  Richard Kaufman   34.65

See the table like structure? 
What looks like a column is actually a `Series` in `pandas`.
The column names are taken from the dictionary that was passed into the constructor function.
Notice that row numbers have been added automatically and start from 0. 
This is the index.
It's possible to specify different row labels when constructing the DataFrame by passing in a value for the optional parameter ``index``.
The index is an instance attribute of the DataFrame so it can be accessed using the dot notation.
Column names can be accessed in a similar way.

In [3]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [4]:
df.columns

Index(['title', 'author', 'price'], dtype='object')

A column Series is selected using square brackets and the column name.
For example:

In [5]:
df["title"]

0             Tangled Web
1                Close Up
2             Foundations
3    Professional Secrets
4               5 Times 5
Name: title, dtype: object

Notice that the row labels are also extracted with the requested column.
To get a single item from the Series use the square bracket notation and the row label, for example:

In [6]:
df["title"][1]

'Close Up'

A few useful DataFrame methods for inspecting your data:
- ``head()`` shows the first few rows of data. By default it will show five rows or you can specify how many.
- ``tail()`` is like ``head()`` but shows the last few rows of data.
- ``describe()`` gives some summary statistics about the numerical columns.
-  ``info()`` returns information such as the column names and their data types.

The ``shape`` of a DataFrame (or Series) is its dimension, the number of rows and columns it has.

In [7]:
df.head(2)

         title       author  price
0  Tangled Web    Eric Mead   40.0
1     Close Up  David Stone   23.1

In [8]:
df.describe()

            price
count    5.000000
mean    92.550000
std    114.489869
min     23.100000
25%     34.650000
50%     40.000000
75%     70.000000
max    295.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   5 non-null      object
 1   author  5 non-null      object
 2   price   5 non-null      float64
dtypes: float64(1), object(2)
memory usage: 248.0+ bytes

In [10]:
df.shape

(5, 3)

## Iterating Over DataFrames
A Pandas Series and a Pandas DataFrame are both iterable. That means we can use them in loops. Let's look at a Series first. For the purposes of a loop, a Series can be treated like a list.

In [11]:
title_series = df["title"]

for i in title_series:
    print('The title of this book is {}'.format(i))

The title of this book is Tangled Web
The title of this book is Close Up
The title of this book is Foundations
The title of this book is Professional Secrets
The title of this book is 5 Times 5

Iterating over a DataFrame directly will only give us the column names.

In [12]:
for i in df:
    print(i)

title
author
price

The ``items()`` method allows us to loop through the columns in turn. Each column is provided as a Series, so we can also loop through the data in the column.

In [13]:
for col_name, col_data in df.items():
    print('**New column: {}**'.format(col_name))
    for i in col_data:
        print(i)

**New column: title**
Tangled Web
Close Up
Foundations
Professional Secrets
5 Times 5
**New column: author**
Eric Mead
David Stone
Eberhard Riese
Geoffrey Durham
Richard Kaufman
**New column: price**
40.0
23.1
70.0
295.0
34.65

To iterate through the rows instead of the columns use ``iterrows()``.

In [15]:
for row_name, row_data in df.iterrows():
    print("**New row: {}**".format(row_name))
    for i in row_data:
        print(i)

**New row: 0**
Tangled Web
Eric Mead
40.0
**New row: 1**
Close Up
David Stone
23.1
**New row: 2**
Foundations
Eberhard Riese
70.0
**New row: 3**
Professional Secrets
Geoffrey Durham
295.0
**New row: 4**
5 Times 5
Richard Kaufman
34.65

Another way to iterate through the rows is with ``itertuples()``, which returns a tuple for each row (remember that a tuple is the same as a list except that it can't be modified once it's created).

In [16]:
for row in df.itertuples(name="Book"):
    print(row)

Book(Index=0, title='Tangled Web', author='Eric Mead', price=40.0)
Book(Index=1, title='Close Up', author='David Stone', price=23.1)
Book(Index=2, title='Foundations', author='Eberhard Riese', price=70.0)
Book(Index=3, title='Professional Secrets', author='Geoffrey Durham', price=295.0)
Book(Index=4, title='5 Times 5', author='Richard Kaufman', price=34.65)

Now we can access a piece of data from each row using the column name. It could also be useful as an intermediate step to creating an object from each of the rows in the DataFrame.

In [17]:
for row in df.itertuples(name="Book"):
    print(row.title)

Tangled Web
Close Up
Foundations
Professional Secrets
5 Times 5

## DataFrame Selecting

We've already looked at how to select a Series (`df["title"]`), but now we'll get fancy with our selects.

First, you can select any columns you'd like in any order (you can even repeat the columns selected), just pass a list of column titles to the indexing `[]` syntax.
This returns a new DataFrame.
The original DataFrame is not affected.

In [18]:
df[["author", "title"]]

            author                 title
0        Eric Mead           Tangled Web
1      David Stone              Close Up
2   Eberhard Riese           Foundations
3  Geoffrey Durham  Professional Secrets
4  Richard Kaufman             5 Times 5

To select specific rows, use `iloc` with a slicing syntax:

In [19]:
df.iloc[2:-1]

                  title           author  price
2           Foundations   Eberhard Riese   70.0
3  Professional Secrets  Geoffrey Durham  295.0

We can mix them too:

In [20]:
df.iloc[2:-1]["title"]

2             Foundations
3    Professional Secrets
Name: title, dtype: object

Rather than selecting blocks of rows, more often you'll find you'll need to filter them based upon some condition. We do this like so:

In [21]:
df[df["price"] > 50]

                  title           author  price
2           Foundations   Eberhard Riese   70.0
3  Professional Secrets  Geoffrey Durham  295.0

You can use any of the numerical comparators (`= != > >= < <=`). The Series also provides an `isin` function, and a `notna` function. `isin` is a membership check, `notna` filters out `na` values.

In [22]:
df[df["title"].isin(["Foundations", "Close Up"])]

         title          author  price
1     Close Up     David Stone   23.1
2  Foundations  Eberhard Riese   70.0

Note, this is a dataframe returned, so you can stack further selectors or filters onto it like so:

In [23]:
df[df["price"] > 50]["author"]

2     Eberhard Riese
3    Geoffrey Durham
Name: author, dtype: object

In [24]:
expensive = df[df["price"] > 50]
not_too_expensive = expensive[expensive["price"] < 100]
not_too_expensive

         title          author  price
2  Foundations  Eberhard Riese   70.0

## Exercise 1

### 1a
The next cell contains some information about the 20 highest-grossing movies. 
At the moment, we have a dictionary for each movie showing the rank, title, the money made (in US $), and the year that the film was released. 

In order to create a DataFrame, we need the data in a different format, namely, a dictionary of lists. 

Write some code to create lists for each type of information (ranking, title, etc.) and use these to create the DataFrame. Give the columns the same names as the current dictionary keys. 

Notice that the ranking, worldwide gross and year data are all presented here as strings. These columns should be converted to integers.

In [25]:
movies = [
    {'Ranking': '1', 'Title': 'Avengers: Endgame', 'Worldwide gross ($)': '2797800564', 'Year': '2019'}, 
    {'Ranking': '2', 'Title': 'Avatar', 'Worldwide gross ($)': '2790439000', 'Year': '2009'}, 
    {'Ranking': '3', 'Title': 'Titanic', 'Worldwide gross ($)': '2194439542', 'Year': '1997'},
    {'Ranking': '4', 'Title': 'Star Wars: The Force Awakens', 'Worldwide gross ($)': '2068223624', 'Year': '2015'},
    {'Ranking': '5', 'Title': 'Avengers: Infinity War', 'Worldwide gross ($)': '2048359754', 'Year': '2018'},
    {'Ranking': '6', 'Title': 'Jurassic World', 'Worldwide gross ($)': '1671713208', 'Year': '2015'},
    {'Ranking': '7', 'Title': 'The Lion King', 'Worldwide gross ($)': '1656943394', 'Year': '2019'},
    {'Ranking': '8', 'Title': 'The Avengers', 'Worldwide gross ($)': '1518812988', 'Year': '2012'},
    {'Ranking': '9', 'Title': 'Furious 7', 'Worldwide gross ($)': '1516045911', 'Year': '2015'},
    {'Ranking': '10', 'Title': 'Frozen II', 'Worldwide gross ($)': '1450026933', 'Year': '2019'},
    {'Ranking': '11', 'Title': 'Avengers: Age of Ultron', 'Worldwide gross ($)': '1402805868', 'Year': '2015'},
    {'Ranking': '12', 'Title': 'Black Panther', 'Worldwide gross ($)': '1347280838', 'Year': '2018'},
    {'Ranking': '13', 'Title': 'Harry Potter and the Deathly Hallows – Part 2', 'Worldwide gross ($)': '1342025430', 'Year': '2011'},
    {'Ranking': '14', 'Title': 'Star Wars: The Last Jedi', 'Worldwide gross ($)': '1332539889', 'Year': '2017'},
    {'Ranking': '15', 'Title': 'Jurassic World: Fallen Kingdom', 'Worldwide gross ($)': '1309484461', 'Year': '2018'},
    {'Ranking': '16', 'Title': 'Frozen', 'Worldwide gross ($)': '1290000000', 'Year': '2013'},
    {'Ranking': '17', 'Title': 'Beauty and the Beast', 'Worldwide gross ($)': '1263521126', 'Year': '2017'},
    {'Ranking': '18', 'Title': 'Incredibles 2', 'Worldwide gross ($)': '1242805359', 'Year': '2018'},
    {'Ranking': '19', 'Title': 'The Fate of the Furious', 'Worldwide gross ($)': '1238764765', 'Year': '2017'},
    {'Ranking': '20', 'Title': 'Iron Man 3', 'Worldwide gross ($)': '1214811252', 'Year': '2013'}
]

In [26]:
df = pd.DataFrame(movies)
df.head()

  Ranking                         Title Worldwide gross ($)  Year
0       1             Avengers: Endgame          2797800564  2019
1       2                        Avatar          2790439000  2009
2       3                       Titanic          2194439542  1997
3       4  Star Wars: The Force Awakens          2068223624  2015
4       5        Avengers: Infinity War          2048359754  2018

In [34]:
for col_name in ['Ranking', 'Worldwide gross ($)', 'Year']:
    df[col_name] = pd.to_numeric(df[col_name])

df.head()

   Ranking                         Title  Worldwide gross ($)  Year
0        1             Avengers: Endgame           2797800564  2019
1        2                        Avatar           2790439000  2009
2        3                       Titanic           2194439542  1997
3        4  Star Wars: The Force Awakens           2068223624  2015
4        5        Avengers: Infinity War           2048359754  2018

### 1b
Select the rows for movies from 2017

In [35]:
df[df['Year'] == 2017]

    Ranking                     Title  Worldwide gross ($)  Year
13       14  Star Wars: The Last Jedi           1332539889  2017
16       17      Beauty and the Beast           1263521126  2017
18       19   The Fate of the Furious           1238764765  2017

### 1c
Select the rows which made at least $1300000000 and were released before 2018.

In [36]:
df[(df['Year'] < 2018) & (df['Worldwide gross ($)'] >= 1300000000)]

,Ranking,Title,Worldwide gross ($),Year
1,2,Avatar,2790439000,2009
2,3,Titanic,2194439542,1997
3,4,Star Wars: The Force Awakens,2068223624,2015
5,6,Jurassic World,1671713208,2015
7,8,The Avengers,1518812988,2012
8,9,Furious 7,1516045911,2015
10,11,Avengers: Age of Ultron,1402805868,2015
12,13,Harry Potter and the Deathly Hallows – Part 2,1342025430,2011
13,14,Star Wars: The Last Jedi,1332539889,2017

### 1d
Create a new DataFrame by selecting the 'Title' and 'Worldwide gross' columns for films released before 2018.

In [40]:
df2 = df[['Title','Worldwide gross ($)']]
df2.head()

                          Title  Worldwide gross ($)
0             Avengers: Endgame           2797800564
1                        Avatar           2790439000
2                       Titanic           2194439542
3  Star Wars: The Force Awakens           2068223624
4        Avengers: Infinity War           2048359754

## Loading, Converting, and Saving Data

We've already seen in previous lessons how to load data from a CSV file, and `pandas` also provides a set of functions to load data from a CSV file directly into a DataFrame. 

The function `read_csv()` takes the names of a CSV file and creates a DataFrame. This DataFrame will take column names from the CSV file automatically, or you can override this behaviour by setting the optional parameters ``header`` to `0` and ``names`` to a list of the column names you would like to use instead.

If you need to load data from an online source, just replace the file name with the URL of the data, `pandas` is smart enough to know what to do.

In [41]:
df = pd.read_csv('http://onlinecourses.leeds.ac.uk/ODL/AI/geek-music.csv')
df

                  Track         Artist                 Album    Time
0         Computer Love      Kraftwerk        Computer World    7:15
1      Paranoid Android      Radiohead           OK Computer    6:27
2          Computer Age     Neil Young                 Trans    5:24
3               Digital   Joy Division                 Still    2:50
4        Silver Machine       Hawkwind             Roadhawks    4:39
5   Start the Simulator           A-Ha  Foot of the Mountain    5:11
6   Internet Connection         M.I.A.                  MAYA    2:56
7             Deep Blue    Arcade Fire           The Suburbs    4:29
8        I Will Derive!  MindofMatthew              You Tube    3:17
9           Lobachevsky     Tom Lehrer              You Tube    3:04
10          Eight Lines    Steve Reich          Shaker Loops  18:13

We've seen this file in a previous lesson, now we're downloading it from the internet directly. 
To save a DataFrame as a CSV use ``to_csv()``. We set ``index=False`` so that the row numbers aren't included in the new file.

In [42]:
df.to_csv("music.csv", index=False)

But what if you need that data in a completely different format? Well `pandas` offers a surprising number of alternative formats. Let's convert it to JSON, if we don't provide a file name to write to, it'll just return the conversion, which is handy for JSON:

In [43]:
df.to_json(orient="records")

'[{"Track":"Computer Love","Artist":"Kraftwerk","Album":"Computer World","Time":"7:15"},{"Track":"Paranoid Android","Artist":"Radiohead","Album":"OK Computer","Time":"6:27"},{"Track":"Computer Age","Artist":"Neil Young","Album":"Trans","Time":"5:24"},{"Track":"Digital","Artist":"Joy Division","Album":"Still","Time":"2:50"},{"Track":"Silver Machine","Artist":"Hawkwind","Album":"Roadhawks","Time":"4:39"},{"Track":"Start the Simulator","Artist":"A-Ha","Album":"Foot of the Mountain","Time":"5:11"},{"Track":"Internet Connection","Artist":"M.I.A.","Album":" MAYA","Time":"2:56"},{"Track":"Deep Blue","Artist":"Arcade Fire","Album":"The Suburbs","Time":"4:29"},{"Track":"I Will Derive!","Artist":"MindofMatthew","Album":"You Tube","Time":"3:17"},{"Track":"Lobachevsky","Artist":"Tom Lehrer","Album":"You Tube","Time":"3:04"},{"Track":"Eight Lines","Artist":"Steve Reich","Album":"Shaker Loops","Time":"18:13 "}]'

## Exercise 2
To be able to follow this exercise you will need a csv file contianing data about the passengers aboarded the famous Titanic ship on its first and only journey. The data for this exercise is available at https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv.

### 2a
Load the CSV file into a DataFrame called 'titanic'.

In [45]:
df_titanic = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv')

### 2b 
Inspect the data - view the first 10 rows

In [46]:
df_titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### 2c
Create a DataFrame called 'titanic_age_sex' which only contains the age and sex of the passengers.

In [51]:
titanic_age_sex = df_titanic[['Sex', 'Age']]
titanic_age_sex.head()

      Sex   Age
0    male  22.0
1  female  38.0
2  female  26.0
3  female  35.0
4    male  35.0

### 2d
Get the subset of data which relates to adults (age greater than or equal to 18), call the new DataFrame 'titanic_adults'.
Check how many rows are in this new DataFrame and compare to the original titanic DataFrame.

In [54]:
titanic_adults = titanic_age_sex[titanic_age_sex['Age'] >= 18]
print(titanic_adults.shape)
print(len(titanic_adults))
print(df_titanic.shape)

(601, 2)
601
(891, 12)

## How to Find Out More

The last thing you need to know is how to discover these functions and how to read their docs so you can read, convert, and write many more formats. There are [docs online](https://pandas.pydata.org/pandas-docs/stable/index.html), or you can make use of `dir` and `help` functions, which is handy to know so you can data-science on your Antarctic expedition, or while flying to meet a client, or when you just don't have a good internet connection.

`dir` lists all the methods of a class, `help` shows the documentation.

In [55]:
# list all the methods in pandas that begin with "read_"
list(filter(lambda m: m.startswith("read_"), dir(pd)))

['read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml']

In [56]:
# list all the methods of DataFrame that begin with "to_"
list(filter(lambda m: m.startswith("to_"), dir(df)))

['to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml']

In [57]:
# print the documentation about the read_csv fundtion in pandas
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, squeeze=None, prefix=<no_default>, mangle_dupe_cols=True, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=None, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression: 'CompressionOptions' = 'infer', thousands=None, decimal: 'str' = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors: 'str | None' = 'strict', dialect=None, error_bad_lines=None, warn_bad_lines=None, on_bad_lines=None, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None, storage_options: 'StorageOptions' = None)
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Delimiter to use. If sep is None, the C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator by Python's builtin sniffer
        tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
        different from ``'\s+'`` will be interpreted as regular expressions and
        will also force the use of the Python parsing engine. Note that regex
        delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, default ``None``
        Alias for sep.
    header : int, list of int, None, default 'infer'
        Row number(s) to use as the column names, and the start of the
        data.  Default behavior is to infer the column names: if no names
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a multi-index on the columns
        e.g. [0,1,3]. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : array-like, optional
        List of column names to use. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : int, str, sequence of int / str, or False, optional, default ``None``
      Column(s) to use as the row labels of the ``DataFrame``, either given as
      string name or column index. If a sequence of int / str is given, a
      MultiIndex is used.

      Note: ``index_col=False`` can be used to force pandas to *not* use the first
      column as the index, e.g. when you have a malformed file with delimiters at
      the end of each line.
    usecols : list-like or callable, optional
        Return a subset of the columns. If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in `names` or
        inferred from the document header row(s). If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        `usecols` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a DataFrame from ``data`` with element order preserved use
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
        in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to True. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    squeeze : bool, default False
        If the parsed data only contains one column then return a Series.

        .. deprecated:: 1.4.0
            Append ``.squeeze("columns")`` to the call to ``read_csv`` to squeeze
            the data.
    prefix : str, optional
        Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...

        .. deprecated:: 1.4.0
           Use a list comprehension on the DataFrame's columns after calling ``read_csv``.
    mangle_dupe_cols : bool, default True
        Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
        'X'...'X'. Passing in False will cause data to be overwritten if there
        are duplicate names in the columns.
    dtype : Type name or dict of column -> type, optional
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32,
        'c': 'Int64'}
        Use `str` or `object` together with suitable `na_values` settings
        to preserve and not interpret dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster, while the python engine
        is currently more feature-complete. Multithreading is currently only supported by
        the pyarrow engine.

        .. versionadded:: 1.4.0

            The "pyarrow" engine was added as an *experimental* engine, and some features
            are unsupported, or may not work correctly, with this engine.
    converters : dict, optional
        Dict of functions for converting values in certain columns. Keys can either
        be integers or column labels.
    true_values : list, optional
        Values to consider as True.
    false_values : list, optional
        Values to consider as False.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : list-like, int or callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (int)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning True if the row should be skipped and False otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with engine='c').
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : scalar, str, list-like, or dict, optional
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values.  By default the following values are interpreted as
        NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'n/a',
        'nan', 'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether `na_values` is passed in, the behavior is as follows:

        * If `keep_default_na` is True, and `na_values` are specified, `na_values`
          is appended to the default NaN values used for parsing.
        * If `keep_default_na` is True, and `na_values` are not specified, only
          the default NaN values are used for parsing.
        * If `keep_default_na` is False, and `na_values` are specified, only
          the NaN values specified `na_values` are used for parsing.
        * If `keep_default_na` is False, and `na_values` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the `keep_default_na` and
        `na_values` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing na_filter=False can improve the performance
        of reading a large file.
    verbose : bool, default False
        Indicate number of NA values placed in non-numeric columns.
    skip_blank_lines : bool, default True
        If True, skip over blank lines rather than interpreting as NaN values.
    parse_dates : bool or list of int or names or list of lists or dict, default False
        The behavior is as follows:

        * boolean. If True -> try parsing the index.
        * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
          result 'foo'

        If a column or index cannot be represented as an array of datetimes,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an object data type. For
        non-standard datetime parsing, use ``pd.to_datetime`` after
        ``pd.read_csv``. To parse an index or column with a mixture of timezones,
        specify ``date_parser`` to be a partially-applied
        :func:`pandas.to_datetime` with ``utc=True``. See
        :ref:`io.csv.mixed_timezones` for more.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If True and `parse_dates` is enabled, pandas will attempt to infer the
        format of the datetime strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.
    keep_date_col : bool, default False
        If True and `parse_dates` specifies combining multiple columns then
        keep the original columns.
    date_parser : function, optional
        Function to use for converting a sequence of string columns to an array of
        datetime instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. Pandas will try to call `date_parser` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by `parse_dates` into a single array
        and pass that; and 3) call `date_parser` once for each row using one or
        more strings (corresponding to the columns defined by `parse_dates`) as
        arguments.
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If True, use a cache of unique, converted dates to apply the datetime
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

        .. versionadded:: 0.25.0
    iterator : bool, default False
        Return TextFileReader object for iteration or getting chunks with
        ``get_chunk()``.

        .. versionchanged:: 1.2

           ``TextFileReader`` is a context manager.
    chunksize : int, optional
        Return TextFileReader object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

        .. versionchanged:: 1.2

           ``TextFileReader`` is a context manager.
    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and '%s' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', or '.zst' (otherwise no compression). If using
        'zip', the ZIP file must contain only one data file to be read in. Set to
        ``None`` for no decompression. Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``} and other
        key-value pairs are forwarded to ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, or ``zstandard.ZstdDecompressor``, respectively. As an
        example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

        .. versionchanged:: 1.4.0 Zstandard support.

    thousands : str, optional
        Thousands separator.
    decimal : str, default '.'
        Character to recognize as decimal point (e.g. use ',' for European data).
    lineterminator : str (length 1), optional
        Character to break file into lines. Only valid with C parser.
    quotechar : str (length 1), optional
        The character used to denote the start and end of a quoted item. Quoted
        items can include the delimiter and it will be ignored.
    quoting : int or csv.QUOTE_* instance, default 0
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
        QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
    doublequote : bool, default ``True``
       When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive quotechar elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        One-character string used to escape other characters.
    comment : str, optional
        Indicates remainder of line should not be parsed. If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter `header` but not by
        `skiprows`. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
        treated as the header.
    encoding : str, optional
        Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

        .. versionchanged:: 1.2

           When ``encoding`` is ``None``, ``errors="replace"`` is passed to
           ``open()``. Otherwise, ``errors="strict"`` is passed to ``open()``.
           This behavior was previously only the case for ``engine="python"``.

        .. versionchanged:: 1.3.0

           ``encoding_errors`` is a new argument. ``encoding`` has no longer an
           influence on how encoding errors are handled.

    encoding_errors : str, optional, default "strict"
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

        .. versionadded:: 1.3.0

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: `delimiter`, `doublequote`, `escapechar`,
        `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
        override values, a ParserWarning will be issued. See csv.Dialect
        documentation for more details.
    error_bad_lines : bool, optional, default ``None``
        Lines with too many fields (e.g. a csv line with too many commas) will by
        default cause an exception to be raised, and no DataFrame will be returned.
        If False, then these "bad lines" will be dropped from the DataFrame that is
        returned.

        .. deprecated:: 1.3.0
           The ``on_bad_lines`` parameter should be used instead to specify behavior upon
           encountering a bad line instead.
    warn_bad_lines : bool, optional, default ``None``
        If error_bad_lines is False, and warn_bad_lines is True, a warning for each
        "bad line" will be output.

        .. deprecated:: 1.3.0
           The ``on_bad_lines`` parameter should be used instead to specify behavior upon
           encountering a bad line instead.
    on_bad_lines : {'error', 'warn', 'skip'} or callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are :

            - 'error', raise an Exception when a bad line is encountered.
            - 'warn', raise a warning when a bad line is encountered and skip that line.
            - 'skip', skip bad lines without raising or warning when they are encountered.

        .. versionadded:: 1.3.0

        .. versionadded:: 1.4.0

            - callable, function with signature
              ``(bad_line: list[str]) -> list[str] | None`` that will process a single
              bad line. ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new list of strings with more elements than
              expected, a ``ParserWarning`` will be emitted while dropping extra elements.
              Only supported when ``engine="python"``

    delim_whitespace : bool, default False
        Specifies whether or not whitespace (e.g. ``' '`` or ``'    '``) will be
        used as the sep. Equivalent to setting ``sep='\s+'``. If this option
        is set to True, nothing should be passed in for the ``delimiter``
        parameter.
    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set False, or specify the type with the `dtype` parameter.
        Note that the entire file is read into a single DataFrame regardless,
        use the `chunksize` or `iterator` parameter to return the data in chunks.
        (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for `filepath_or_buffer`, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.
    float_precision : str, optional
        Specifies which converter the C engine should use for floating-point

In [60]:
# print the documentation about the to_csv method of DataFrame
help(df.to_csv)

Help on method to_csv in module pandas.core.generic:

to_csv(path_or_buf: 'FilePath | WriteBuffer[bytes] | WriteBuffer[str] | None' = None, sep: 'str' = ',', na_rep: 'str' = '', float_format: 'str | None' = None, columns: 'Sequence[Hashable] | None' = None, header: 'bool_t | list[str]' = True, index: 'bool_t' = True, index_label: 'IndexLabel | None' = None, mode: 'str' = 'w', encoding: 'str | None' = None, compression: 'CompressionOptions' = 'infer', quoting: 'int | None' = None, quotechar: 'str' = '"', line_terminator: 'str | None' = None, chunksize: 'int | None' = None, date_format: 'str | None' = None, doublequote: 'bool_t' = True, escapechar: 'str | None' = None, decimal: 'str' = '.', errors: 'str' = 'strict', storage_options: 'StorageOptions' = None) -> 'str | None' method of pandas.core.frame.DataFrame instance
    Write object to a comma-separated values (csv) file.

    Parameters
    ----------
    path_or_buf : str, path object, file-like object, or None, default None
        String, path object (implementing os.PathLike[str]), or file-like
        object implementing a write() function. If None, the result is
        returned as a string. If a non-binary file object is passed, it should
        be opened with `newline=''`, disabling universal newlines. If a binary
        file object is passed, `mode` might need to contain a `'b'`.

        .. versionchanged:: 1.2.0

           Support for binary file objects was introduced.

    sep : str, default ','
        String of length 1. Field delimiter for the output file.
    na_rep : str, default ''
        Missing data representation.
    float_format : str, default None
        Format string for floating point numbers.
    columns : sequence, optional
        Columns to write.
    header : bool or list of str, default True
        Write out the column names. If a list of strings is given it is
        assumed to be aliases for the column names.
    index : bool, default True
        Write row names (index).
    index_label : str or sequence, or False, default None
        Column label for index column(s) if desired. If None is given, and
        `header` and `index` are True, then the index names are used. A
        sequence should be given if the object uses MultiIndex. If
        False do not print fields for index names. Use index_label=False
        for easier importing in R.
    mode : str
        Python write mode, default 'w'.
    encoding : str, optional
        A string representing the encoding to use in the output file,
        defaults to 'utf-8'. `encoding` is not supported if `path_or_buf`
        is a non-binary file object.
    compression : str or dict, default 'infer'
        For on-the-fly compression of the output data. If 'infer' and '%s'
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', or '.zst' (otherwise no compression). Set to
        ``None`` for no compression. Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``} and other
        key-value pairs are forwarded to ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, or ``zstandard.ZstdDecompressor``, respectively. As an
        example, the following could be passed for faster compression and to create
        a reproducible gzip archive:
        ``compression={'method': 'gzip', 'compresslevel': 1, 'mtime': 1}``.

        .. versionchanged:: 1.0.0

           May now be a dict with key 'method' as compression mode
           and other entries as additional compression options if
           compression mode is 'zip'.

        .. versionchanged:: 1.1.0

           Passing compression options as keys in dict is
           supported for compression modes 'gzip', 'bz2', 'zstd', and 'zip'.

        .. versionchanged:: 1.2.0

            Compression is supported for binary file objects.

        .. versionchanged:: 1.2.0

            Previous versions forwarded dict entries for 'gzip' to
            `gzip.open` instead of `gzip.GzipFile` which prevented
            setting `mtime`.

    quoting : optional constant from csv module
        Defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
        then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
        will treat them as non-numeric.
    quotechar : str, default '\"'
        String of length 1. Character used to quote fields.
    line_terminator : str, optional
        The newline character or character sequence to use in the output
        file. Defaults to `os.linesep`, which depends on the OS in which
        this method is called ('\\n' for linux, '\\r\\n' for Windows, i.e.).
    chunksize : int or None
        Rows to write at a time.
    date_format : str, default None
        Format string for datetime objects.
    doublequote : bool, default True
        Control quoting of `quotechar` inside a field.
    escapechar : str, default None
        String of length 1. Character used to escape `sep` and `quotechar`
        when appropriate.
    decimal : str, default '.'
        Character recognized as decimal separator. E.g. use ',' for
        European data.
    errors : str, default 'strict'
        Specifies how encoding and decoding errors are to be handled.
        See the errors argument for :func:`open` for a full list
        of options.

        .. versionadded:: 1.1.0

    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib`` as header options. For other URLs (e.g.
        starting with "s3://", and "gcs://") the key-value pairs are forwarded to
        ``fsspec``. Please see ``fsspec`` and ``urllib`` for more details.

        .. versionadded:: 1.2.0

    Returns
    -------
    None or str
        If path_or_buf is None, returns the resulting csv format as a
        string. Otherwise returns None.

    See Also
    --------
    read_csv : Load a CSV file into a DataFrame.
    to_excel : Write DataFrame to an Excel file.

    Examples
    --------
    >>> df = pd.DataFrame({'name': ['Raphael', 'Donatello'],
    ...                    'mask': ['red', 'purple'],
    ...                    'weapon': ['sai', 'bo staff']})
    >>> df.to_csv(index=False)
    'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'

    Create 'out.zip' containing 'out.csv'

    >>> compression_opts = dict(method='zip',
    ...                         archive_name='out.csv')  # doctest: +SKIP
    >>> df.to_csv('out.zip', index=False,
    ...           compression=compression_opts)  # doctest: +SKIP

    To write a csv file to a new folder or nested folder you will first
    need to create it using either Pathlib or os:

    >>> from pathlib import Path  # doctest: +SKIP
    >>> filepath = Path('folder/subfolder/out.csv')  # doctest: +SKIP
    >>> filepath.parent.mkdir(parents=True, exist_ok=True)  # doctest: +SKIP
    >>> df.to_csv(filepath)  # doctest: +SKIP

    >>> import os  # doctest: +SKIP
    >>> os.makedirs('folder/subfolder', exist_ok=True)  # doctest: +SKIP
    >>> df.to_csv('folder/subfolder/out.csv')  # doctest: +SKIP

# Solutions to Exercises
## 1
### 1a

In [ ]:
movies = [
    {'Ranking': '1', 'Title': 'Avengers: Endgame', 'Worldwide gross ($)': '2797800564', 'Year': '2019'}, 
    {'Ranking': '2', 'Title': 'Avatar', 'Worldwide gross ($)': '2790439000', 'Year': '2009'}, 
    {'Ranking': '3', 'Title': 'Titanic', 'Worldwide gross ($)': '2194439542', 'Year': '1997'},
    {'Ranking': '4', 'Title': 'Star Wars: The Force Awakens', 'Worldwide gross ($)': '2068223624', 'Year': '2015'},
    {'Ranking': '5', 'Title': 'Avengers: Infinity War', 'Worldwide gross ($)': '2048359754', 'Year': '2018'},
    {'Ranking': '6', 'Title': 'Jurassic World', 'Worldwide gross ($)': '1671713208', 'Year': '2015'},
    {'Ranking': '7', 'Title': 'The Lion King', 'Worldwide gross ($)': '1656943394', 'Year': '2019'},
    {'Ranking': '8', 'Title': 'The Avengers', 'Worldwide gross ($)': '1518812988', 'Year': '2012'},
    {'Ranking': '9', 'Title': 'Furious 7', 'Worldwide gross ($)': '1516045911', 'Year': '2015'},
    {'Ranking': '10', 'Title': 'Frozen II', 'Worldwide gross ($)': '1450026933', 'Year': '2019'},
    {'Ranking': '11', 'Title': 'Avengers: Age of Ultron', 'Worldwide gross ($)': '1402805868', 'Year': '2015'},
    {'Ranking': '12', 'Title': 'Black Panther', 'Worldwide gross ($)': '1347280838', 'Year': '2018'},
    {'Ranking': '13', 'Title': 'Harry Potter and the Deathly Hallows – Part 2', 'Worldwide gross ($)': '1342025430', 'Year': '2011'},
    {'Ranking': '14', 'Title': 'Star Wars: The Last Jedi', 'Worldwide gross ($)': '1332539889', 'Year': '2017'},
    {'Ranking': '15', 'Title': 'Jurassic World: Fallen Kingdom', 'Worldwide gross ($)': '1309484461', 'Year': '2018'},
    {'Ranking': '16', 'Title': 'Frozen', 'Worldwide gross ($)': '1290000000', 'Year': '2013'},
    {'Ranking': '17', 'Title': 'Beauty and the Beast', 'Worldwide gross ($)': '1263521126', 'Year': '2017'},
    {'Ranking': '18', 'Title': 'Incredibles 2', 'Worldwide gross ($)': '1242805359', 'Year': '2018'},
    {'Ranking': '19', 'Title': 'The Fate of the Furious', 'Worldwide gross ($)': '1238764765', 'Year': '2017'},
    {'Ranking': '20', 'Title': 'Iron Man 3', 'Worldwide gross ($)': '1214811252', 'Year': '2013'}
]

ranking = [int(m["Ranking"]) for m in movies]
title = [m["Title"] for m in movies]
money = [int(m["Worldwide gross ($)"]) for m in movies]
year = [int(m["Year"]) for m in movies]

df = pd.DataFrame({
    "Ranking": ranking,
    "Title": title,
    "Worldwide gross ($)": money,
    "Year": year
})

df

### 1b

In [ ]:
df[df["Year"]==2019]

### 1c

In [ ]:
df2 = df[df["Worldwide gross ($)"] >= 1300000000]
df2[df2["Year"] < 2018]

### 1d

In [ ]:
df3 = df[df["Year"] < 2018][['Title', 'Worldwide gross ($)']]
df3

## 2
### 2a

In [ ]:
titanic = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv')

### 2b

In [ ]:
titanic.head(10)

### 2c

In [ ]:
titanic_age_sex = titanic[['Age', 'Sex']]
titanic_age_sex.head()

### 2d

In [ ]:
titanic_adults = titanic[titanic['Age'] >= 18]

# get the number of records in the new DF and original
titanic.shape , titanic_adults.shape